#include <iostream>
#include "game.h"
using namespace std;



int main() {
  Player StarterCharacter("Noob", 24, 10 );
  Game *test = new Game(5, 5, 0, 0, StarterCharacter);
  test->playGame();
  
  delete test;
} 


/*
What map do you want to load? (Make sure to include .txt)
Map.txt
P....
.....
.....
.....
.....
Which direction do you want to move? (W, A, S, D)
s
You've found a mana potion. Your mana is now : 20
Do you want to keep exploring the game world? (Type no to quit)
y
 ....
P....
.....
.....
.....
Which direction do you want to move? (W, A, S, D)
s
You've found a mana potion. Your mana is now : 30
Do you want to keep exploring the game world? (Type no to quit)
y
 ....
M....
P....
.....
.....
Which direction do you want to move? (W, A, S, D)
d
You've found a crystal.
Do you want to keep exploring the game world? (Type no to quit)
y
 ....
M....
MP...
.....
.....
Which direction do you want to move? (W, A, S, D)
w
You've found a Pumpkin.
Do you want to keep exploring the game world? (Type no to quit)
y
 ....
MP...
MC...
.....
.....
Which direction do you want to move? (W, A, S, D)
w
Do you want to keep exploring the game world? (Type no to quit)
y
 P...
MP...
MC...
.....
.....
Which direction do you want to move? (W, A, S, D)
d
You've discovered an Ancient Golem. It seems lifeless but strong.
Armed to the teeth with an assortments of items and abilities, do you dare challenge the beast? (Y or N)y

You place the crystal inside the pumpkin and attempt to raise a golem. Your mana reserves pour ample energy in and the pumpkins exterior hardens with the help of the crystal. The battle is swift and victory is yours. You claim the treasure the golem was guarding. 


 Congratulations! Game cleared.
*/